[#15] Feature: Purchase, Sale, Trade 엔티티 및 서비스, API 구현
f-lab-edu/unique-auction pull request #16
Opened 2022-09-25 08:30 UTC by vymr1000

**관련된 이슈 번호**
- issue : #15 

**요약**
- 구매자 & 판매자 입찰 등록 및 거래 기능

**변경사항 (할 일)**
PR에 반영되어야 할 변경 사항들을 작성 해주세요.

- [ ] purchase, sale, trade 엔티티 구현 
- [ ] 즉시 구매 & 입찰 등록 서비스 및 API 구현
- [ ] 즉시 판매 & 입찰 등록 서비스 및 API 구현

2022-09-26 01:43 UTC, f-lab-lion commented on src/main/java/com/uniqueAuction/domain/trade/entity/Purchase.java
> +	}
enum을 별도의 class가 아닌 Purchase 내부에 선언한 이유가 있나요?

2022-09-26 13:42 UTC, vymr1000 commented on src/main/java/com/uniqueAuction/domain/trade/entity/Purchase.java
> +	}
해당 status enum이 purchase, sale, trade 부분에 각각 존재하는데 각 타입이 엔티티에 종속적이라 생각하여 내부에 선언하였으나.. e해당 enum이 중복된다고 할 수 있어서 공통화 하였습니다.

2022-09-27 01:55 UTC, f-lab-lion commented on src/main/java/com/uniqueAuction/domain/trade/entity/Trade.java
> +public class Trade {
다른 엔티티는 생성자에 `@Builder`가 사용되었습니다.
`Trade`는 class에 `@Builder`가 사용된 이유가 있나요?

2022-09-27 03:28 UTC, vymr1000 commented on src/main/java/com/uniqueAuction/domain/trade/entity/Trade.java
> +public class Trade {
@Builder 모든 필드에 대해 예외없이 파라미터로 받아 생성할 것이기 때문에 클래스 레벨의 어노테이션을 사용하였습니다.

2022-09-27 13:36 UTC, f-lab-lion approved these changes
LGTM!!

2022-09-27 13:37 UTC, f-lab-lion requested changes
:)

2022-09-29 12:23 UTC, f-lab-lion commented on src/main/java/com/uniqueAuction/domain/trade/entity/Trade.java
> +public class Trade {
그렇다면 아래쪽에 생성자는 불필요한것 아닌가요?
https://github.com/f-lab-edu/unique-auction/pull/16/files#diff-37e87e496bcaa283cb4bfd45bd831b58ff91d1c9c3d87c7dadd7b9a179dc2ef4R19

사소한 내용이긴하지만 개발 컨밴션을 정하고 한가지로 통일하면 좋겠습니다.

`Trade`에 필드가 추가되면 어떤 일이 생길까요?
만약에 필드를 추가하는사람이 생성자쪽으로 `@Builder`를 옮기지 않는경우, 
`Trade` class에 추가되는 모든 필드에 대해서 예외없이 파라메터로 받는것으로 개발규칙이 정해집니다.
그게 아니라면 반드시 생성자쪽으로 `@Builder`를 옮겨야한다는 규칙이 됩니다.(하지만 이부분은 실수가 발생하기 쉬운 부분이 됩니다.)

반대로 생성자에 붙이는경우를 선택하셨다면 앞으로 필드가 추가될때 개발자가 판단하여 생성자쪽에도 추가해주어야한다는 규칙이 생깁니다.

2022-09-29 12:31 UTC, f-lab-lion commented on src/main/java/com/uniqueAuction/domain/trade/entity/TradeType.java
> +    SALE_BID /* 판매 입찰 */
설계관련해서 질문드립니다~
`TradeType`은 거래 관련된 타입인것같습니다.
거래는 한건이고, 유저가 보는 관점에 따라 한사람이 판매를하면 한사람은 구입을 하게 됩니다.
`Trade`관점으로 보자면 즉시(거래) / 입찰(거래) 이렇게 2가지 타입이 있는것은 아닌가요?

만약 구분하고자 한다면 `SaleType`, `PulchaseType` 으로 구분해야하는것은 아닌가요?
실제로 service layer를 보면 TradeService가 아닌 `SaleService`, `PulchaseService`로 되어있습니다

2022-09-30 04:47 UTC, vymr1000 commented on src/main/java/com/uniqueAuction/domain/trade/entity/TradeType.java
> +    SALE_BID /* 판매 입찰 */
파일이 생성하게 되면서 관리 포인트가 늘어나는거에 대해 고민이 있었던 것 같습니다. 보다 의미를 명확하기 하기 위해 enum 나누는 것이 저도 좋다고 생각합니다.

2022-09-30 04:47 UTC, vymr1000 commented on src/main/java/com/uniqueAuction/domain/trade/entity/Trade.java
> +public class Trade {
감사합니다 그 부분 고려해서 적절하게 적용하도록 하겠습니다.

2022-09-30 16:23 UTC, superkkj commented
Transaction

2022-09-30 16:25 UTC, superkkj approved these changes

2022-10-01 04:24 UTC, merged